package co.edu.usbcali.demojasper.modelo;
// Generated Mar 3, 2018 11:07:36 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer clieId;
     private String nombreCompleto;
     private String identificacion;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(Integer clieId, String nombreCompleto, String identificacion) {
        this.clieId = clieId;
        this.nombreCompleto = nombreCompleto;
        this.identificacion = identificacion;
    }
    public Cliente(Integer clieId, String nombreCompleto, String identificacion, Set<Factura> facturas) {
       this.clieId = clieId;
       this.nombreCompleto = nombreCompleto;
       this.identificacion = identificacion;
       this.facturas = facturas;
    }
   
    public Integer getClieId() {
        return this.clieId;
    }
    
    public void setClieId(Integer clieId) {
        this.clieId = clieId;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


