package co.edu.usbcali.demojasper.modelo;
// Generated Mar 3, 2018 11:07:36 PM by Hibernate Tools 5.1.0.Final

/**
 * DetalleFactura generated by hbm2java
 */
public class DetalleFactura implements java.io.Serializable {

	private Integer defaId;
	private Factura factura;
	private Producto producto;
	private Double cantidad;

	public DetalleFactura() {
	}

	public DetalleFactura(Integer defaId, Factura factura, Producto producto, Double cantidad) {
		this.defaId = defaId;
		this.factura = factura;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public Integer getDefaId() {
		return this.defaId;
	}

	public void setDefaId(Integer defaId) {
		this.defaId = defaId;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Double getCantidad() {
		return cantidad;
	}

	public void setCantidad(Double cantidad) {
		this.cantidad = cantidad;
	}

}
