package co.edu.usbcali.demojasper.modelo;
// Generated Mar 3, 2018 11:07:36 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer factId;
     private Cliente cliente;
     private Date fecha;
     private String cabecera;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Factura() {
    }

	
    public Factura(Integer factId, Cliente cliente, Date fecha, String cabecera) {
        this.factId = factId;
        this.cliente = cliente;
        this.fecha = fecha;
        this.cabecera = cabecera;
    }
    public Factura(Integer factId, Cliente cliente, Date fecha, String cabecera, Set<DetalleFactura> detalleFacturas) {
       this.factId = factId;
       this.cliente = cliente;
       this.fecha = fecha;
       this.cabecera = cabecera;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getFactId() {
        return this.factId;
    }
    
    public void setFactId(Integer factId) {
        this.factId = factId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getCabecera() {
        return this.cabecera;
    }
    
    public void setCabecera(String cabecera) {
        this.cabecera = cabecera;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


