package co.edu.usbcali.demojasper.modelo;
// Generated Mar 3, 2018 11:07:36 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer prodId;
     private String descripcion;
     private Double valorUnitario;
     private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

    public Producto() {
    }

	
    public Producto(Integer prodId, String descripcion, Double valorUnitario) {
        this.prodId = prodId;
        this.descripcion = descripcion;
        this.valorUnitario = valorUnitario;
    }
    public Producto(Integer prodId, String descripcion, Double valorUnitario, Set<DetalleFactura> detalleFacturas) {
       this.prodId = prodId;
       this.descripcion = descripcion;
       this.valorUnitario = valorUnitario;
       this.detalleFacturas = detalleFacturas;
    }
   
    public Integer getProdId() {
        return this.prodId;
    }
    
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getValorUnitario() {
        return this.valorUnitario;
    }
    
    public void setValorUnitario(Double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }
    public Set<DetalleFactura> getDetalleFacturas() {
        return this.detalleFacturas;
    }
    
    public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
        this.detalleFacturas = detalleFacturas;
    }




}


